package edu.dartmouth.cs.xiankai_yang.stressmeter;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ImageView;
import android.widget.Toast;

public class DetailActivity extends AppCompatActivity {
    public static final String SCORE = "Score";

    private static final String TAG = "Detail Activity";

    int imageId;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_detail);

        imageId = getIntent().getIntExtra(RecordFragment.IMAGE_ID, -1);

        if (imageId != -1) {
            ((ImageView) findViewById(R.id.selected_image)).setImageResource(imageId);
        } else {
            Log.d(TAG, "Image id is -1!");
            finish();
        }
    }

    public void onClickSubmit(View view) {
        Intent intent = new Intent();
        // The score the generated by its resource id (randomly)
        intent.putExtra(SCORE, imageId % RecordFragment.IMAGE_NUM_PER_PAGE);
        setResult(RESULT_OK, intent);
        finish();
    }

    public void onClickCancel(View view) {
        Intent intent = new Intent();
        setResult(RESULT_CANCELED, intent);
        finish();
    }
}
