package edu.dartmouth.cs.xiankai_yang.stressmeter;

/**
 * Created by yangxk15 on 1/24/17.
 */

import android.graphics.Color;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TableLayout;
import android.widget.TableRow;
import android.widget.TextView;

import java.io.File;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.AxisValue;
import lecho.lib.hellocharts.model.Line;
import lecho.lib.hellocharts.model.LineChartData;
import lecho.lib.hellocharts.model.PointValue;
import lecho.lib.hellocharts.view.LineChartView;

public class ResultFragment extends Fragment {
    private static final String TAG = "Result Fragment";

    @Override
    public View onCreateView(LayoutInflater inflater,
                             ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_result, container, false);

        // Initialize line point and axis
        List<PointValue> pointValues = new ArrayList<>();
        List<AxisValue> xValues = new ArrayList<>();
        List<AxisValue> yValues = new ArrayList<>();

        try {
            List<Map.Entry<Timestamp, Integer>> list = new FileHelper(this.getActivity()).readFromFile();

            for (Map.Entry<Timestamp, Integer> entry : list) {
                // Add to points and axis
                pointValues.add(new PointValue(pointValues.size(), entry.getValue()));
                xValues.add(new AxisValue(xValues.size()));
                yValues.add(new AxisValue(entry.getValue()));

                // Add to table
                TableRow tableRow = new TableRow(getActivity());
                TextView textView1 = new TextView(getActivity());
                TextView textView2 = new TextView(getActivity());
                textView1.setText(" " + entry.getKey().toString());
                textView1.setBackgroundResource(R.drawable.cell);
                textView2.setText(" " + entry.getValue().toString());
                textView2.setBackgroundResource(R.drawable.cell);
                tableRow.addView(textView1);
                tableRow.addView(textView2);
                ((TableLayout) view.findViewById(R.id.table)).addView(tableRow);

                Log.d(TAG, entry.getKey() + "," + entry.getValue());
            }

            // Set Line Chart
            Line line = new Line(pointValues).setColor(Color.BLUE).setCubic(true);
            List<Line> lines = new ArrayList<>();
            lines.add(line.setFilled(true));
            LineChartData data = new LineChartData();
            data.setLines(lines);
            data.setAxisXBottom(new Axis(xValues)
                    .setName("Instances")
                    .setAutoGenerated(true));
            data.setAxisYLeft(new Axis(yValues)
                    .setName("Stress Level")
                    .setAutoGenerated(true)
                    .setHasLines(true));
            ((LineChartView) view.findViewById(R.id.line_chart))
                    .setLineChartData(data);

        } catch (Exception e) {
            Log.d(TAG, e.getMessage());
        }

        return view;
    }

}
